### ISSUE TITLE
Cannacake Babe Vegan Treat Pics Cut Off

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#100]
Location: https://spicygreenbook.org/biz/cannacakebabe-vegan-treats

Problem: Photos on the right are cut off not showing the whole picture. I tried re-ordering them in prismic to show different shots but to no success. This may be an issue of design that would need to be fixed as opposed to working on re-ordering pictures as that has failed on my account for this listing. 

<img width="1364" alt="Screen Shot 2020-11-11 at 8 42 53 PM" src="https://user-images.githubusercontent.com/69876068/98896773-a0e7be80-245e-11eb-9324-c112851dac31.png">

 - OS: [iOS]
 - Browser [chrome]

**Comment by pleaseshutup** [comment]
There are 3 possible solutions that I can think of:

1. Offer a crop position for the images to specify left/top/right/bottom/center top, bottom right etc in order to specify where the image gets cropped to fit within the provided designs aspect ratio for the image slot. We can put this in prismic but it may not solve the problem. Please talk to a designer that understands this to help determine the ideal solution. They should be roughly familiar with the variance in images that are provided for a listing.

2. Get a new design for this section that can feature 1 or multiple images per listing that does not have any aspect ratio constraints so any image(s) can be used

3. Use only wide aspect ratio images that fit within the provided design for the first 3 images.

**Comment by danilobatson** [comment]
Would trying out option 1 be easiest then if that doesn't work move to option 2?
