### ISSUE TITLE
Website: Browse Page (Title, search bar and page name)

### ISSUE THREAD

**Issue by lorenitademani** [spicygreenbook/greenbook-app#105]
Changes on Browse Page:

1) Page name: rename to browse
2) The search bar on the Browse Page should match the one on the home page. 
3) Add page's title on top of the page

Please see pic for details. 
![Browse Page](https://user-images.githubusercontent.com/73954798/98963466-a6ccb680-24d5-11eb-9656-7d5b173d63c3.jpg)

**Comment by pleaseshutup** [comment]
Hi, Thanks for the suggestion.
The browse and search pages are the same endpoint with the same functionality. "Browse" is simply the search results page without a keyword or location provided to narrow results. This will stay the same for now. Our vision is to have so many listings the user has to search and narrow results instead of just browse.
