### ISSUE TITLE
Sky Gourmet Tacos 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#11]
Photos are not fully displayed on the individual listing page or the new listing scroll. 

Can only see the top of the quesadilla

**Comment by pleaseshutup** [comment]
the design enforces a specific aspect ratio for an image. They are wide aspect ratios e.g. 16:9

That taco shop photo's are taller than they are wide and have to be cropped to fit into the design's provided aspect ratio to fill the shape. Because of this they are getting cropped but not at a flattering spot. I can't know the content of the image to know if it should show the top/left/right/bottom side of the image when it fits it into the container.

The fastest solution would be to choose a wider photo for the first 3 photos of the listing.

**Comment by danilobatson** [comment]
Okay I re-ordered them on prismic. Hopefully it is better. Can't see yet as the deploy is not successful up to this point.

**Comment by pleaseshutup** [comment]
better images are in looks good now.
