### ISSUE TITLE
High Priority: Loading Delay 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#124]
**Describe the bug**
Website is having delays. Not loading as quickly as we would hope. I put some screenshots showcasing the delay. Can't put video on here. 

**To Reproduce**
1. Go to 'spicygreenbook.org'
2. Type in your search item 
3. Click search
4. See error (showcased in the screenshot) 

<img width="936" alt="Screen Shot 2020-11-16 at 4 30 00 PM" src="https://user-images.githubusercontent.com/69876068/99324418-0950ea00-2829-11eb-9a50-a1359ce965dc.png">

**Desktop (please complete the following information):**
 - OS: [ macOS Catalina Version 10.15.7] 
 - Browser [chrome]

**Comment by pleaseshutup** [comment]
The search page seems slow because the SSR rendering of the page is missing the styles and something is causing this page to re-render multiple times. We may have to consider pagination, however, this will conflict with a request to have the items randomly sorted which logically conflicts with pagination.

First gotta solve the page being rendered properly in the initial render from the server and then when that's fixed we can sort out optimization of the re-renders and possible pagination.

**Comment by danielpquinn** [comment]
I think we can avoid reloading this page by using the next router instead of updating window.location. I'll try that really quick and see if it fixes the issue.

I agree that SSR is the root of the problem and we'll need to figure out how to load css at the same time as the initial page load instead of waiting for React Native to generate it via javascript.

**Comment by pleaseshutup** [comment]
@danielpquinn hrm I must have let that slip through a PR. the search component is supposed to do react router navigation just noticed now it was changed to window.location = 

i patched that just now.

**Comment by danielpquinn** [comment]
Nice! I was just about to open a PR when I saw your change come through, thanks!

**Comment by pleaseshutup** [comment]
I think I got it.
actual trick in 465ae4b2482f3f40e00bee0c02436f1963a2c94a
final tweak in c86e874e252eaa3494ce27c0ba69d333d060ad9e when I realized i had used the example markup not our custom document
and this was the fix for search doing window.location
013132dcbdaee560741c3000e40cf18cd0ddd069
