### ISSUE TITLE
Download Our Flyer 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#237]
Would like a button to download our flyer on the add listing page. The button should look like the subscribe button in the screen shot below and should read "Download Our Flyer" and take you to this link: 

https://prismic-io.s3.amazonaws.com/spicygreenbook/04cb42ed-a40b-4199-835a-ee1b5f5f6982_SGB+Flyer.pdf

It currently is hyperlinked in the text. So the button can go right below said text. 

![image](https://user-images.githubusercontent.com/69876068/104644962-54d61780-5663-11eb-945f-4cf94732062d.png)

![image](https://user-images.githubusercontent.com/69876068/104645054-6a4b4180-5663-11eb-875e-58f8d7ca7fc5.png)

**Comment by JeroenGoddijn** [comment]
@danilobatson Little bit of a challenge here, since the content block loaded from CMS contains both text block as well as the 6-step image. 

Standard implementation will result in the button showing below the 6-step image. (basicall:, it will just show button underneath whatever content is loaded from CMS)

We can manipulate DOM and try to inject the button above the image or below the last paragraph, but that could result in weird results when content gets updated in CMS in the future.

Please let us know IF and HOW you want to proceed with this request. I added some images to show how it would look like with the standard implementation.

A 3rd option would be to add the button as a 3rd button next to the bottom image (where the other 2 buttons already are).

![localhost_3000_add](https://user-images.githubusercontent.com/48567344/105094485-f85f6780-5a69-11eb-90d4-1c5ec791e034.png)

![localhost_3000_add(iPhone 6_7_8)](https://user-images.githubusercontent.com/48567344/105094488-f8f7fe00-5a69-11eb-882b-191eb2567f2f.png)

**Comment by danilobatson** [comment]
@JeroenGoddijn I am okay with it being below the 6-step infographic

**Comment by danilobatson** [comment]
@JeroenGoddijn could do the smaller version from the mockups you sent. If it is close to fill out our form button the user can more clearly see they have two options

**Comment by JeroenGoddijn** [comment]
> @JeroenGoddijn could do the smaller version from the mockups you sent. If it is close to fill out our form button the user can more clearly see they have two options

The smaller version is just mobile web version vs the laptop web version in larger image. 

I can put it underneath the 6-step image easily, just let me know if you prefer the button positioned LEFT/CENTER/RIGHT

**Comment by danilobatson** [comment]
@JeroenGoddijn I think right is best

**Comment by JeroenGoddijn** [comment]
@danilobatson Submitted the enhancement. You decide if you want to leave the text link above the 6-step image as well or whether you want to remove that...
