### ISSUE TITLE
URGENT: Volunteer Page 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#258]
**Describe the bug**
The different roles on the volunteer page don't expand so you can see the job duties 

**To Reproduce**
1. Go to 'spicygreenbook.org/volunteer'
2. Click on 'the +'
3. See error

**Expected behavior**
The copy should expand so you can see the duties of each role

**Screenshots**
![image](https://user-images.githubusercontent.com/69876068/105220739-fb5f6400-5b0c-11eb-8be3-70aa7505134e.png)

**Desktop (please complete the following information):**
 - OS: iOS]
 - Browser [ chrome]

**Comment by C-Garza** [comment]
This looks like another issue when `react-native-web` was upgraded to version 13 in [this commit](https://github.com/spicygreenbook/greenbook-app/commit/79e1926a01a7ec218979becbf2c9ea123efa8146). The issue is with `react-native-gesture-handler` and it's described in [this link here](https://github.com/software-mansion/react-native-gesture-handler/issues/1164#issuecomment-684013868).

Possible solutions are to downgrade `react-native-web` or to upgrade `react-native-gesture-handler` to at least `~1.9.0`. 

I upgraded `react-native-gesture-handler` in my local branch and it seems to work just fine but I haven't really tested if there were any breaking changes. Can look more into it tomorrow unless someone else picks this up by then.

**Comment by JeroenGoddijn** [comment]
> This looks like another issue when `react-native-web` was upgraded to version 13 in [this commit](https://github.com/spicygreenbook/greenbook-app/commit/79e1926a01a7ec218979becbf2c9ea123efa8146). The issue is with `react-native-gesture-handler` and it's described in [this link here](https://github.com/software-mansion/react-native-gesture-handler/issues/1164#issuecomment-684013868).
> 
> Possible solutions are to downgrade `react-native-web` or to upgrade `react-native-gesture-handler` to at least `~1.9.0`.
> 
> I upgraded `react-native-gesture-handler` in my local branch and it seems to work just fine but I haven't really tested if there were any breaking changes. Can look more into it tomorrow unless someone else picks this up by then.

Running `npm upgrade react-native-gesture-handler@1.9.0` seems to fix it for me too, when I test locally.
