### ISSUE TITLE
Directory Filter 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#262]
Looking to implement a filter section on the directory page. 

See design 

https://xd.adobe.com/view/cf0156f6-6214-4065-8024-64d8b4618e95-9a52/

![image](https://user-images.githubusercontent.com/69876068/105565253-cdc81580-5cda-11eb-915c-efe627466027.png)

![image](https://user-images.githubusercontent.com/69876068/105565231-b2f5a100-5cda-11eb-943b-2beff155d750.png)

**Comment by pleaseshutup** [comment]
To do this we would have to add the price classification to prismic and on every listing as well as any of those features that apply to a listing.

In order to do "currently open" we'd have to have their hours in a way that can be parsed by a machine to determine if the users browser/device is within the hours they are open.

So we can't do this until all the data is in prismic for the listings. Let me know if this is the finalized list of what we want because its going to take a lot of effort to put this data into prismic and i want to be sure we have all the different points of data we want for now and the future before going through that effort.

Also this is premature given how many listings we have especially if a user only has 1-5 in their area IMO but it can certainly be done

**Comment by danilobatson** [comment]
@pleaseshutup If we have to put all that data into prismic we should actually implement data points now before we have to go back and re-do it all on a ton of listings. Let me gather the data points.

**Comment by danilobatson** [comment]
@pleaseshutup I am looking on Yelp and I think the following checks would be good options for the user for filtering. Let me know your thoughts: 

1. Open Now
2. Alcohol
3. Price filter 
4. Takes Reservation 
5. Vegan options 
6. Vegetarian options
7. Gluten-Free options
8. Meals 
9. Offers Delivery 
10. Wi-Fi 
11. Distance

**Comment by pleaseshutup** [comment]
Seems ok to me but my point was to think through all of the data you want to assosiate with a business, consult with the listings and others to really have a solid plan. Then we update prismic. Then we update the app to allow for this. 

Most of the listings will have to be updated before we can even offer this feature. Since that will take a lot of time and effort I do recommend a lot of thought is put into it before the data is gathered. I recommend we close this issue until that is planned, prismic updated with the ability to put the data in correctly and then most of the listings are updated with this data. Until then this task cannot be started by a developer.
