### ISSUE TITLE
Footer Social Media Links Logos 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#267]
For the Social Media links in the footer of the site we currently have IG, Facebook, LinkedIn, and YouTube. I would like to add a few more. 

1. Add our GitHub. 
2. Add our Behance. https://www.behance.net/spicygreenbook/
3. Add our Pinterest. https://www.pinterest.com/spicygreenbook
4. Add email linked logo. admin@spicygreenbook.org

**Comment by C-Garza** [comment]
I can do this. I'll add it as another row under the existing one.

**Comment by JeroenGoddijn** [comment]
@C-Garza Keep an eye on issue [198](https://github.com/spicygreenbook/greenbook-app/issues/198) in which the Footer design seems to change.
So, try to implement a flexible solution, so that the Social Media Links/Icons adjust accordingly, when the Footer gets redesigned as shown in design file attached to issue 198.

You can also wait for @gkemp94 to deploy his solution for issue 198, so you can implement and test yours on the new situation...

Anyway...just wanted to make you aware of that change ;)

**Comment by C-Garza** [comment]
Hey @JeroenGoddijn, it looks like that section was already added in [this commit](https://github.com/spicygreenbook/greenbook-app/commit/15fa5647cbb9fe866d0d25953f90c19455bba4b8). They must have forgotten to close the issue, that design seems to be on the site.

I've just added the social links, so I'll make a pull request soon.

**Comment by JeroenGoddijn** [comment]
Interesting... The design in that issue just shows the footer without the Newsletter subscription in there, and instead have the FooterNav links placed left of Social Links...

They probably either forgot to request the changes to the Footer or perhaps decided to not remove the newsletter section from the footer...

**Comment by C-Garza** [comment]
It looks like the footer newsletter came after that issue here in #203. Here it is being suggested a couple days after that issue.
