### ISSUE TITLE
App Sub Level Pages Back Button And Bottom Menu

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#363]
![image](https://user-images.githubusercontent.com/69876068/112913124-ef17fa00-90ad-11eb-88d3-824b82c19a44.png)

**Comment by JeroenGoddijn** [comment]
@danilobatson : Just FYI, but I'm getting a 404 error, as it seems you are linking to an email attachment (to which none of us will probably have access, since it sits in your inbox) ;) Not sure if that's the case, but that's what the error message suggests. So, you might have to upload the doc to Google Drive or something and share it from there. This probably applies to all the issues where you link to this audit file.

**Comment by mrvncaragay** [comment]
will look into this.

**Comment by JeroenGoddijn** [comment]
Thanks, @mrvncaragay

**Comment by mrvncaragay** [comment]
updated 0d93f2941e7911865a6f3067511f1776c5786194
