### ISSUE TITLE
App Malfunction 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#426]
**Describe the bug**
The App is crashing whenever you click on a listing. 

**To Reproduce**
1. Open App
2. In search bar type in 'All Flavor No Grease' in 'Los Angeles, CA'
3. Click on listing 

**Expected behavior**
Listing should show where you can see the business information and the gallery. 

Note: A few days ago a listing would show but the app would not render any photos in the gallery. Currently after clicking on listing you only get a blank screen. 

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - Apple Store

**Comment by C-Garza** [comment]
The issue is in the `Listing.js` file shown here:
https://github.com/spicygreenbook/greenbook-app/blob/c990e52fe53e987fa00a075ba03fd94b3984f042/screens/Listing.js#L221

For that particular listing, they don't have a cuisines length, so `0` is being rendered on screen, which crashes on the app because text has to be in a `<Text>` component. I can make a quick PR to fix this issue.
