### ISSUE TITLE
Mobile App: Search field box not centered

### ISSUE THREAD

**Issue by likeawesome** [spicygreenbook/greenbook-app#77]
Search not vertically aligned. Too much space on the right side.

Severity: 1
1 | Cosmetic problem only
2 | Minor usability problem; fixing this should be given low priority
3 | Major usability problem; important to fix, high priority
4 | Usability catastrophe; must be fixed before product can be released

![iOS14-2-iPhone11_7631](https://user-images.githubusercontent.com/74067650/98773356-00ce5e80-23a6-11eb-8fa0-7fbe6d438c0e.jpg)

**Comment by pleaseshutup** [comment]
For whomever takes on this task.
Lets have it fit the width with equal margins on each side *until* the point where it converts to the larger version of the search nav. Also please test different widths to ensure we convert to the larger nav (more text/bigger) at the appropriate widths on both the home page and the search results page.

**Comment by danielpquinn** [comment]
I had to touch the search input layout to add the "use location" dropdown in this PR: https://github.com/spicygreenbook/greenbook-app/pull/136. I used flexbox to position everything in the search component, so it will properly stretch to the full width on mobile. This issue will be fixed with PR 136.
