### ISSUE TITLE
Design/development assistance 

### ISSUE THREAD

**Issue by danilobatson** [spicygreenbook/greenbook-app#84]
Looking for some ux assistance. 

When you look for listings on on spicy green book it is hard to tell what category a business falls under. Such as grocery store products, food truck, retail, pop-up, pick-up & delivery, catering, restaurant, or the mix of a few. 

From the ux as you search it can become difficult as they pursue to find food options near them. An example would be [](https://spicygreenbook.com/biz/8-myles )which is only located in grocery stores or [](https://spicygreenbook.com/biz/pinckney-cookie-cafe which is exclusively shipping through online ordering. 

We'd love for someone to make this more notable for the user. 

It would be great if someone were to search for BBQ near them and it was clear if it was a food truck, pop-up only, etc. 

Would make it easier to locate the business. 

If you wish to take on this task, please let us know. Be sure to test on ios/android and all web browser screen sizes.

**Comment by pleaseshutup** [comment]
I am not sure if the github issues list is the right audience for this task. This seems like a ux designer task not a developer task and I am not sure they are browsing this list. I am going to close this issue since I don't think it can be handled by any developer that shows up here easily as it is missing clear direction. Please discuss this in the #product channel in the SGB slack and then open an issue when you've been able to procure the design/direction from someone.
